[project]
name = "nlp_assignment-1"
version = "0.1.0"
description = "pyproject.toml file for NLP assignment 1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "scikit-learn>=1.8.0",
]
